{% set name = "lsdb" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/lsdb/archive/v{{ version }}.tar.gz
  sha256: b4d80c846476e13cd311fb18a933c277190a22192ad842258c12cea6027c5138

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - dask
    - jinja2
    - hipscat >=0.2.4
    - pyarrow
    - deprecated
    - ipykernel
    - scipy
    - lsst-sphgeom

test:
  imports:
    - lsdb
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - pytest-timeout
  source_files:
    - tests

about:
  home: https://github.com/astronomy-commons/lsdb
  summary: 'Large Survey Database (LSDB), an large astronomical catalog analytics tool'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mjuric
    - jeremykubica
    - drewoldag
    - delucchi-cmu
