{% set python_min = "3.11" %}
{% set version = "0.10.0" %}

package:
  name: lsdb-split
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/h/hats/hats-{{ version }}.tar.gz
    sha256: 1c9680bdf55556da07991e07a6f99bf6e2eb2d98008cfb23fada34468fd55d7f
    folder: hats
  - url: https://pypi.org/packages/source/h/hats_import/hats_import-{{ version }}.tar.gz
    sha256: f8af9c9547efd8c88b779a9384fbb2fa9149fc87798c5594734b11b25590443d
    folder: hats-import
  - url: https://pypi.org/packages/source/l/lsdb/lsdb-{{ version }}.tar.gz
    sha256: 830c49dc00437c76efbcc8996c8223ddce1852bb791698f1d7931f5f1345ce7e
    folder: lsdb

build:
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
  run:
    - python {{ python_min }}

outputs:
  - name: hats

    build:
      noarch: python
      script: cd hats && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      number: 0

    requirements:
      host:
        - python {{ python_min }}
        - setuptools >=62
        - setuptools-scm >=6.2
        - pip
      run:
        - python >={{ python_min }}
        - aiohttp >=3.8.0
        - astropy-base >=6.1.5
        - cdshealpix >=0.8.0
        - fsspec >=2023.10.0
        - human-readable
        - jinja2
        - jproperties >=2.0.0
        - mocpy >=0.19.0
        - nested-pandas >=0.6.7,<0.7.0
        - numba >=0.58
        - numpy >=2,<3
        - pandas >=2.0
        - pyarrow >=14.0.1,!=19.0.0
        - pydantic >=2.0
        - scipy >=1.7.2
        - typing-extensions >=4.3.0
        - universal_pathlib >=0.3.1

    test:
      imports:
        - hats
      commands:
        - pip check
        - cd hats && pytest tests --log-cli-level=INFO
      requires:
        - pip
        - pytest
        - pytest-mock
        - pytest-timeout
        - python {{ python_min }}
      source_files:
        - hats/tests

  - name: lsdb

    build:
      noarch: python
      script: cd lsdb && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      number: 0

    requirements:
      host:
        - python {{ python_min }}
        - setuptools >=62
        - setuptools-scm >=6.2
        - pip
      run:
        - python >={{ python_min }}
        - dask >=2025.3.0
        - deprecated
        - hats >={{ version }},<0.11
        - lsst-sphgeom
        - nested-pandas >=0.6.7,<0.7.0
        - numpy
        - pyarrow
        - scipy >=1.7.2
        - tabulate >=0.7.0
        - tqdm >=4.59.0
        - universal_pathlib

    test:
      imports:
        - lsdb
      commands:
        - pip check
        - cd lsdb && pytest tests
      requires:
        - pip
        - pytest
        - pytest-mock
        - python {{ python_min }}
      source_files:
        - lsdb/tests

  - name: hats-import

    build:
      noarch: python
      script: cd hats-import && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      number: 0

    requirements:
      host:
        - python {{ python_min }}
        - setuptools >=62
        - setuptools-scm >=6.2
        - pip
      run:
        - python >={{ python_min }}
        - cloudpickle >=3.0.0
        - dask-core >=2024.3.0,<2025.4.0
        - deprecated
        - distributed
        - hats >={{ version }},<0.11
        - ipykernel
        - nested-pandas >=0.6.7,<0.7.0
        - numpy >=2.2.0,<3
        - pandas >=2.0
        - tqdm >=4.59.0
        - universal_pathlib

    test:
      imports:
        - hats_import
      commands:
        - pip check
        - cd hats-import && pytest tests --timeout=0
      requires:
        - pip
        - pytest
        - pytest-timeout
        - pytest-mock
        - python {{ python_min }}
      source_files:
        - hats-import/tests
        - hats-import/pyproject.toml

about:
  home: https://github.com/astronomy-commons/lsdb
  summary: 'LSDB, python tool for scalable analysis of large catalogs'
  license: BSD-3-Clause
  license_file: lsdb/LICENSE

extra:
  recipe-maintainers:
    - smcguire-cmu
    - olivialynn
    - gitosaurus
    - dougbrn
    - hombit
    - astronomy-commons/lincc-frameworks
    - camposandro
    - delucchi-cmu
    - drewoldag
    - jeremykubica
    - mjuric
