{% set python_min = "3.10" %}
{% set name = "lsdb" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/lsdb/archive/v{{ version }}.tar.gz
  sha256: 2322ac9d24215c4c4d34a7a1ff0e401f08532164db8b0381f4c92eac0f055e7f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - dask >=2025.3.0
    - deprecated
    - hats >=0.6.1
    - lsst-sphgeom
    - nested-pandas >=0.4.6,<0.5.0
    - numpy >=2
    - pyarrow >=14.0.1,!=19.0.0
    - scipy >=1.7.2
    - universal_pathlib >=0.2.2
    - jinja2

test:
  imports:
    - lsdb
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - pytest-mock
    - python {{ python_min }}
  source_files:
    - tests

about:
  home: https://github.com/astronomy-commons/lsdb
  summary: 'LSDB, python tool for scalable analysis of large catalogs'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - camposandro
    - delucchi-cmu
    - drewoldag
    - jeremykubica
    - mjuric
