{% set name = "lsdb" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/lsdb/archive/v{{ version }}.tar.gz
  sha256: f7e7a3e65e80890eb997df0aa4bf3ce7300961c1c38152a37780ea7d2b7e9f6a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - dask
    - deprecated
    - hats >=0.4.3
    - lsst-sphgeom
    - nested-dask >=0.3.0
    - nested-pandas
    - numpy <2
    - pyarrow
    - scipy
    - jinja2

test:
  imports:
    - lsdb
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - pytest-mock
  source_files:
    - tests

about:
  home: https://github.com/astronomy-commons/lsdb
  summary: 'Large Survey Database (LSDB), an large astronomical catalog analytics tool'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - camposandro
    - delucchi-cmu
    - drewoldag
    - jeremykubica
    - mjuric
